name: Security Scans

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install --upgrade pip && pip install -r requirements.txt
      - name: Run Bandit Security Scan
        run: |
          bandit -r . -f html -o bandit-report.html || true
      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.html

  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install --upgrade pip && pip install -r requirements.txt
      - name: Start Flask App
        run: |
          nohup python app.py > app.log 2>&1 &
          sleep 10
          curl --retry 5 --retry-connrefused --silent --fail http://localhost:8000 || (echo "Flask app failed to start" && exit 1)
      - name: Pull ZAP Docker Image (Fixes Permission Issues)
        run: |
          docker pull ghcr.io/zaproxy/zaproxy:stable
      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          allow_issue_writing: false
        with:
          target: 'http://localhost:8000'
          cmd_options: '-J report_json.json -w report_md.md -r report_html.html'
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-zap-report
          path: owasp-zap-report.html
